export const REQUEST_SPELL = 'REQUEST_SPELL';
export const RECEIVE_SPELL = 'RECEIVE_SPELL';
export const CHANGE_SPELL = 'CHANGE_SPELL';
export const DELETE_SPELL = 'DELETE_SPELL';
export const REQUEST_DIRECTORY_LIST = 'REQUEST_DIRECTORY_LIST';
export const RECEIVE_DIRECTORY_LIST = 'RECEIVE_DIRECTORY_LIST';
